// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuYi6cgs7qfbTRZBzf09hNpQA4m71knlA',
    appId: '1:181744204342:web:eaabb1205c53e8b2d57697',
    messagingSenderId: '181744204342',
    projectId: 'ventzor',
    authDomain: 'ventzor.firebaseapp.com',
    storageBucket: 'ventzor.firebasestorage.app',
    measurementId: 'G-K4C5BKF625',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzSiscqZTsbkjtJ9Hikg4zmuEdB3CSWFA',
    appId: '1:181744204342:android:e7dba37afdf27008d57697',
    messagingSenderId: '181744204342',
    projectId: 'ventzor',
    storageBucket: 'ventzor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGznWUVZSZr9vGbi2f34TWhH_f_5W9ra0',
    appId: '1:181744204342:ios:d52b3a27aa8886b1d57697',
    messagingSenderId: '181744204342',
    projectId: 'ventzor',
    storageBucket: 'ventzor.firebasestorage.app',
    iosBundleId: 'com.flashtorial.ventzor',
  );
}
